# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: edwardelricwzx@gmail.com
author_name: catwang01
has_binder: true
has_settings: true
kind: server
labextension_name: jupyterlab-snips
project_short_description: A JupyterLab extension.
python_name: jupyterlab_snips
repository: https://github.com/catwang01/jupyterlab-snips
test: true

